name: Bug report
description: Something isn't working as intended?
labels: [Bug, "Meta: Needs triage", "Lang: Korean"]
body:
  - type: markdown
    attributes:
      value: |
        ### 검색 먼저

        먼저 [열린 이슈](https://github.com/7thbeatgames/adofai/issues?q=is%3Aissue+is%3Aopen)를 검색하여 이미 다른 사람이 관련 이슈를 제출했는지 확인해보세요.

        해당 이슈가 중복되었다면 관리자는 제출한 이슈를 종료 처리하게 됩니다. 중복된 이슈를 새로 만드는 대신, 다른 사람이 제출한 이슈에 👍 이모트를 달아주세요.

        ### 한국어 안내

        비록 한국어를 지원 대상에 포함하고 있기는 하나, 개발자들은 영어를 표준으로 쓰고 있습니다. 때문에 개발자들은 대부분 기계 번역으로 한국어 이슈를 접하게 됩니다.

        한국어로는 의사 소통이 다소 원활하지 않을 수 있는 점 양해를 부탁드리며, 기계 번역이 원활히 될 수 있도록 문법을 지키며 글을 작성해주시기 바랍니다.

        ### 자주 묻는 질문 확인

        [자주 묻는 질문](https://7thbeat.notion.site/ADOFAI-8dc4ef47b27d465cb90c792a51ccb543) 페이지에 답변이 이미 있을 수도 있습니다.
  - type: checkboxes
    attributes:
      label: 중복 확인
      description: 버그가 이미 보고되었는지 검색해보시기 바랍니다.
      options:
        - label: 이슈를 검색했고, 중복이 없는지를 확인했습니다.
          required: true
  - type: textarea
    id: summaryKR
    attributes:
      label: 요약
      description: 버그를 간단히 요약하세요. 짧으면서도 효과적으로 문제를 요약해주시기 바랍니다.
    validations:
      required: true
  - type: input
    id: versionKR
    attributes:
      label: 버전
      description: 게임 메인 화면의 하단에서 버전 정보를 확인할 수 있습니다.
      placeholder: 예시) v0.11.3 (r23)
    validations:
      required: true
  - type: input
    id: osKR
    attributes:
      label: 운영체제 (OS)
      description: 어떤 운영체제를 사용하고 계신가요?
      placeholder: 예시) 윈도우즈 11 / macOS 몬터레이 (M1/인텔) / iOS / 안드로이드 등
    validations:
      required: true
  - type: input
    id: platformKR
    attributes:
      label: 플랫폼
      description: 어떤 플랫폼을 이용하고 계신가요?
      placeholder: 예시) 스팀 / itch.io / 앱 스토어 / 플레이 스토어 등
    validations:
      required: true
  - type: input
    id: deviceInfoKR
    attributes:
      label: 기기 정보
      description: 어떤 기기를 이용하고 계신가요?
      placeholder: 예시) 아이폰 13 / 삼성 갤럭시 노트 22 등
    validations:
      required: false
  - type: textarea
    id: stepsToReproduceKR
    attributes:
      label: 재현 방법
      description: 버그를 재현하는 방법을 적어주세요.
      placeholder: |
        1. 1단계
        2. 2단계
        3. 3단계
        4. 오류 발생
    validations:
      required: true
  - type: textarea
    id: expectedBehaviorKR
    attributes:
      label: 예상 결과
      description: 실행되길 기대했던 결과를 적어주세요.
    validations:
      required: true
  - type: textarea
    id: observedBehaviorKR
    attributes:
      label: 실제 결과
      description: 실제로 일어난 결과를 적어주세요.
    validations:
      required: true
  - type: input
    attributes:
      label: 재현율
      description: 재현 방법을 통해 버그가 얼마나 자주 발생하는지 적어주세요. (100%, 3번 중 1번 등)
      placeholder: 예시) 100%, 33%, 드물게 등
  - type: textarea
    attributes:
      label: 그 외
      description: |
        스크린샷, 비디오, 로그 파일 등 문제와 관련된 설명을 더욱 자세하게 해주세요.
        하단 텍스트 상자를 클릭한 후 파일을 드래그 앤 드롭하여 첨부할 수 있습니다.
        
        게임 화면에서 [Ctrl + Shift + L] 키를 눌러 로그가 저장되는 폴더를 볼 수 있습니다.