name: 기능 제안
description: 제안이 있으신가요
labels: [Suggestion, "Meta: Needs triage", "Lang: Korean"]
body:
  - type: markdown
    attributes:
      value: |
        ### 안내사항
        
        먼저 [열린 이슈](https://github.com/7thbeatgames/adofai/issues?q=is%3Aissue+is%3Aopen)를 검색하여 이미 다른 사람이 관련 이슈를 제출했는지 확인해보세요.

        해당 이슈가 중복되었다면 관리자는 제출한 이슈를 종료 처리하게 됩니다. 중복된 이슈를 새로 만드는 대신, 다른 사람이 제출한 이슈에 👍 이모트를 달아주세요.

        7th Beat Games는 지적 재산권 또는 기타 방식에 따른 의무, 로열티나 제한 없이 자사 제품 또는 서비스에 대한 피드백을 무제한적으로 사용, 복사, 공개, 라이선스 부여, 배포 및 활용할 수 있습니다. 7th Beat Games는 피드백의 수용 여부 관계 없이 제품 또는 서비스를 독립적으로 사용, 개발, 평가 또는 마케팅할 수 있는 권리를 보유합니다. 이 조항에 동의하지 않는다면 제안을 제출하지 마십시오.
  - type: checkboxes
    attributes:
      label: 체크사항
      options:
        - label: 이슈를 검색했고, 중복이 없는지를 확인했습니다.
          required: true
        - label: 제안은 추가 또는 반영이 보장되지 않는다는 점을 이해했습니다.
          required: true
  - type: textarea
    id: currentIssueKR
    attributes:
      label: 제안하고자 하는 점은 무엇인가요? 어떤 문제 때문에 제안을 하게 되었나요?
      description: 문제를 명확하고 자세하게 설명해주세요.
    validations:
      required: true
  - type: textarea
    id: suggestedSolutionKR
    attributes:
      label: 해결 방법
      description: 어떤 일이 일어나길 원하는지 명확하고 간결하게 설명해주세요.
    validations:
      required: true
  - type: textarea
    id: alternativeKR
    attributes:
      label: 대체 방안
      description: 문제를 해결하기 위해 시도해봤던 대안적 방법이나 기능이 있나요?
  - type: textarea
    id: demoKR
    attributes:
      label: 데모 및 목업
      description: 제안하고자 하는 기능을 소개하는 이미지나 비디오를 첨부하세요.
  - type: textarea
    id: noteKR
    attributes:
      label: 그 외
      description: 제안과 관련된 기타 설명을 적어주세요.